CREATE SCHEMA `BD0124`;

-- Criação da tabela

CREATE TABLE `BD0124`.`USUARIO`(
	`ID_USUARIO` INTEGER NOT NULL AUTO_INCREMENT,
	`NOME` VARCHAR(30) NOT NULL,
	`GENERO` VARCHAR(30) NOT NULL,
	`NASCIMENTO` DATE NOT NULL,
	`EMAIL` VARCHAR(100) NOT NULL,
	`RUA` VARCHAR(100) NOT NULL,
	`BAIRRO` VARCHAR(50) NOT NULL,
	`CIDADE` VARCHAR(50) NOT NULL,
	`ESTADO` VARCHAR(2) NOT NULL,
	`PAIS` VARCHAR(50) NOT NULL,
	`NUMERO` INTEGER NOT NULL,
	`CEP` INTEGER NOT NULL,
	PRIMARY KEY (`ID_USUARIO`)
);	

-- Inserção de dados

INSERT INTO `BD0124`.`USUARIO` (`NOME`, `GENERO`, `NASCIMENTO`, `EMAIL`, `RUA`, `BAIRRO`, `CIDADE`, `ESTADO`, `PAIS`, `NUMERO`, `CEP`) 
VALUES('João Danielewicz', 'Masculino', 20040916, 'joao@joao.com', 'Rua Aerial', 'Tal', 'Videira', 'SC', 'Brasil', 89, 89560000);
select * from `BD0124`.`USUARIO`


