CREATE SCHEMA IMOBILIARIA;
USE IMOBILIARIA;

CREATE TABLE LOCALIDADE(
	LOCALIDADE_ID INT NOT NULL AUTO_INCREMENT,
    NOME_TIPO_LOCALIDADE VARCHAR(20) NOT NULL,
    PRIMARY KEY(LOCALIDADE_ID)
);

CREATE TABLE TIPO_IMOVEL(
	TIPO_IMOVEL_ID INT NOT NULL AUTO_INCREMENT,
    NOME_TIPO_IMOVEL VARCHAR(100) NOT NULL,
    PRIMARY KEY(TIPO_IMOVEL_ID)
);

CREATE TABLE TIPO_NEGOCIO(
	TIPO_NEGOCIO_ID INT NOT NULL AUTO_INCREMENT,
    NOME_TIPO_NEGOCIO VARCHAR(20) NOT NULL,
    PRIMARY KEY(TIPO_NEGOCIO_ID)
);



CREATE TABLE IMOVEL (
	IMOVEL_ID INT AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    VALOR FLOAT NOT NULL,
    QTD_COMODOS INT NOT NULL,
    LOCALIDADE_ID INT NOT NULL,
    TIPO_IMOVEL_ID INT NOT NULL,
    TIPO_NEGOCIO_ID INT NOT NULL,
    PRIMARY KEY(IMOVEL_ID),
    FOREIGN KEY(LOCALIDADE_ID) REFERENCES LOCALIDADE(LOCALIDADE_ID),
    FOREIGN KEY(TIPO_IMOVEL_ID) REFERENCES TIPO_IMOVEL(TIPO_IMOVEL_ID),
    FOREIGN KEY(TIPO_NEGOCIO_ID) REFERENCES TIPO_NEGOCIO(TIPO_NEGOCIO_ID)
);


CREATE TABLE IMAGEM(
	IMAGEM_ID INT AUTO_INCREMENT NOT NULL,
    IMAGEM LONGBLOB,
    IMOVEL_ID INT NOT NULL,
    PRIMARY KEY(IMAGEM_ID),
    FOREIGN KEY(IMOVEL_ID) REFERENCES IMOVEL(IMOVEL_ID)
);



