CREATE DATABASE EMPRESA;
USE EMPRESA;

CREATE TABLE FUNCIONARIO(
	ID_FUNCIONARIO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    MATRICULA INT NOT NULL,
    NOME VARCHAR(256) NOT NULL,
    DT_NASC DATETIME NOT NULL,
    NACIONALIDADE VARCHAR(256) NOT NULL,
    GENERO VARCHAR(256) NOT NULL,
    EST_CIVIL VARCHAR(256) NOT NULL,
    RG INT NOT NULL,
    ENDERECO VARCHAR(256) NOT NULL,
    TELEFONE VARCHAR(256) NOT NULL,
    DT_ADMISSAO DATETIME NOT NULL
);

CREATE TABLE CARGO(
	NOME_CARGO VARCHAR(256) NOT NULL,
    DEPARTAMENTO VARCHAR(256) NOT NULL,
    DT_INICIO DATETIME NOT NULL,
    DT_FIM DATETIME NOT NULL,
    ID_FUNCIONARIO INT NOT NULL,
    PRIMARY KEY (ID_FUNCIONARIO, NOME_CARGO, DEPARTAMENTO),
    CONSTRAINT FK_ID_FUNCIONARIO_CARGO FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIO(ID_FUNCIONARIO)
);

CREATE TABLE DEPENDENTE(
	ID_DEPENDENTE INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(256) NOT NULL,
    DT_NASC DATETIME NOT NULL,
    ID_FUNCIONARIO INT NOT NULL,
    CONSTRAINT FK_ID_FUNCIONARIO_DEPENDENTE FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIO(ID_FUNCIONARIO)
);

INSERT INTO FUNCIONARIO(MATRICULA, NOME,DT_NASC,NACIONALIDADE,GENERO,EST_CIVIL,RG,ENDERECO,TELEFONE,DT_ADMISSAO) VALUES
			(12, 'Sebastião', 19160613, 'Brasileiro', 'Masculino', 'Solteiro', '123586','Cambé - PR', '49 9 58887425', 19950125),
            (78, 'Kate Bush', 19580730, 'Inglesa', 'Feminina', 'Casada', '587896','Devon', '03 5478269', 19780120),
            (97, 'Kati Outinen', 19610817, 'Finlandesa', 'Feminina', 'Solteira', '376814','Vaasa', '45 8847524', 20010519);
            
INSERT INTO CARGO(NOME_CARGO, DEPARTAMENTO, DT_INICIO, DT_FIM, ID_FUNCIONARIO) VALUES
			('Guardião', 'Doméstico', 19170815, current_timestamp(), 1),
            ('Cantora', 'Cultural', 19750220, current_timestamp(), 2),
            ('Atriz', 'Cultural', 19901014, current_timestamp(), 3),
            ('Atriz', 'Cultural', 19910101, 19910101, 2);

INSERT INTO DEPENDENTE(NOME, DT_NASC, ID_FUNCIONARIO) VALUES
			('Robert', 19980916, 2);
                 
select * from funcionario;


