-- CLIENTES QUE COMPRARAM BANANA
SELECT
	NF.NRO_NOTA AS NUMERO, 
    NF.NOME_CLIENTE AS CLIENTE,
    INF.DESC_PRODUTO AS PRODUTO,
    INF.QTD_PRODUTO AS QUANTIDADE
FROM 
	NOTA_FISCAL AS NF,
	ITEM_NOTA_FISCAL AS INF,
    PRODUTO AS PRD
WHERE
	NF.NRO_NOTA = INF.NRO_NOTA
	AND INF.COD_PRODUTO = PRD.COD_PRODUTO
    AND PRD.COD_PRODUTO = 1
ORDER BY 
	QUANTIDADE DESC;
    
-- /////////////////////////////////////////////
-- CLIENTES QUE MAIS COMPRAM
    
SELECT 
	NF.NOME_CLIENTE AS CLIENTE,
    SUM(INF.VALOR_TOTAL) AS VALOR
FROM
	NOTA_FISCAL AS NF,
    ITEM_NOTA_FISCAL AS INF
WHERE
	NF.NRO_NOTA = INF.NRO_NOTA
GROUP BY
	NF.NOME_CLIENTE
ORDER BY
    VALOR DESC;
    
-- /////////////////////////////////////////////
-- CLIENTES QUE MAIS COMPRAM
    
SELECT
	PRD.DESC_PRODUTO AS PRODUTO,
    COUNT(INF.COD_PRODUTO) AS QUANTIDADE
FROM
    ITEM_NOTA_FISCAL AS INF,
    PRODUTO AS PRD
WHERE 
	INF.COD_PRODUTO = PRD.COD_PRODUTO
GROUP BY
	PRODUTO
ORDER BY
	QUANTIDADE
DESC;


